### ISSUE TITLE
Can't enable Hermes

### ISSUE THREAD

**Issue by ejkkan** [obytes/react-native-template-obytes#100]
# Summary:
Hey, first of all. Thanks for the template, it's great!

I have a couple of question that I'm not able to get around.

I'm trying to enable hermes via app.config.ts. But it's seems like it's not respected when I set it either a the root(`jsEnginge="hermes"`) on under `ios.jsEnginge="hermes"`.
It works on other project for me. Is there somehint about this projects setup that prevents it?

## Steps to reproduce:
Add hermes setup to app.config.ts
rebuild with "npm run ios", for example.

## Expected behavior:
Hermes is enabled

**Comment by yjose** [comment]
@ejkkan I think you missed running `npm run  prebuild` before running `npm run ios` as we are using custom dev client with expo, whenever you update the config file `app.config.ts` you will need to run prebuild
