### ISSUE TITLE
react-native-make is archived

### ISSUE THREAD

**Issue by KBSchmidt** [obytes/react-native-template-obytes#11]
Hi!

You have a really nice template here, I think I'll use it for the next project :)   I was checking the dependecies and looks like react-native-make is no longer maintained. I'm not sure what's going on at Bamlab, they even have a [deprecation notice](https://github.com/bamlab/generator-rn-toolbox#%EF%B8%8F-deprecation-notice-%EF%B8%8F) for an other package of theirs, stating they're migrating that packages capabilites to react-native-make.

I use fastlane for app icons, but since SVGs are already part of this template, you might want to take a look at [this package](https://github.com/aeirola/react-native-svg-app-icon).

**Comment by yjose** [comment]
👋  thank you @KBSchmidt, for reporting this,
Yeah, you are right, react-native-make is no longer maintained, but till now, it's working without issues
I will test the package you suggested and search for another alternative soon.

**Comment by nimeshpoudel7** [comment]
@yjose why expo , cant we make only on cli?

**Comment by yjose** [comment]
Not using th his package anymore as we switch to use expo custom dev client.
