### ISSUE TITLE
none-commit env variables handling

### ISSUE THREAD

**Issue by ejkkan** [obytes/react-native-template-obytes#110]
# Summary:

Interested in hearing how people are using env variables with the eas.json setup.
This setup makes it so that you should add sensitive information to your file. For all of you envirionments. 
Preferably one would not want to commit these files, using `react-native-dotenv` for example.
But `process.env` variables can't really be used in the `eas.json`

How do you solve this?

**Comment by ejkkan** [comment]
Anyone?

**Comment by yjose** [comment]
Hey @ejkkan , We update how we manage our environment variables to using `.env` files, you can check the complete guide [here](https://starter.obytes.com/docs/getting-started/environment-vars-config). 

With the new approach you can easily use inline environment variables depend on the platform you are triggering the build from. so for example you can add your prod environment variables as GitHub secrets and  pass them to your prod workflow. this way you are making sure that your prod credential are secure. 
Let me know if you need more details ?

**Comment by ejkkan** [comment]
Amazing, thanks for that!
