### ISSUE TITLE
Error: react-native-mmkv is not supported in Expo Go! Use EAS (`expo prebuild`) or eject to a bare workflow instead.

### ISSUE THREAD

**Issue by dev-jaskaranSingh** [obytes/react-native-template-obytes#111]
# Summary:
IOS Expo : Error: react-native-mmkv is not supported in Expo Go! Use EAS (`expo prebuild`) or eject to a bare workflow instead.

## Steps to reproduce:
- yarn install
- expo start
-  scan QR code and this error happen

Error screenshot : https://prnt.sc/8WOPbHvTfqPx

**Comment by yjose** [comment]
@dev-jaskaranSingh  thank you for opning the issue 
can you set the mmkv version to '2.5.1' and try again  
Probably  as you install dps, mmkv version has been updated to '2.6.1' which not working correctly with RN 0.70  [source](https://github.com/mrousavy/react-native-mmkv/releases/tag/v2.6.1)

**Comment by yjose** [comment]
@dev-jaskaranSingh  expo GO is not supported as we are using a [custom dev client with expo  ](https://starter.obytes.com/docs/getting-started/create-new-app#running-the-app)
