### ISSUE TITLE
forwardRef ControlledInput

### ISSUE THREAD

**Issue by NadeemKhanFh** [obytes/react-native-template-obytes#117]
#forwardRef ControlledInput:

Hi @yjose thanks for great template, can you please tell me how to forwardRef ControlledInput which is used in the template.,

**Comment by yjose** [comment]
Hey @NadeemKhanFh  thank you for your kind words
Not sure what you are trying to do as the `ControlledInput` is supposed to only work with `react-hook-form` as used in the auth form [here](https://github.com/obytes/react-native-template-obytes/blob/master/src/screens/login/login-form.tsx)  and you dont need to pass a ref instance to make it work.

Any way i see what you want to do and its a little bit tricky to make the forwardRef function working with a function component that accept typescript template. but here is the solution you are looking for:

replace the `ControlledInput` with the following code and it should work with ref: 
```tsx
import * as React from 'react';
import type {
  Control,
  FieldValues,
  Path,
  RegisterOptions,
} from 'react-hook-form';
import { useController } from 'react-hook-form';
import type { TextInput } from 'react-native';

import type { NInputProps } from './input';
import { Input } from './input';

type TRule = Omit<
  RegisterOptions,
  'valueAsNumber' | 'valueAsDate' | 'setValueAs'
>;

export type RuleType<T> = { [name in keyof T]: TRule };
export type InputControllerType<T extends FieldValues> = {
  name: Path<T>;
  control: Control<T>;
  rules?: TRule;
};

interface ControlledInputProps<T extends FieldValues>
  extends NInputProps,
    InputControllerType<T> {}

// only used with react-hook-form
function NControlledInput<T extends FieldValues>(
  props: ControlledInputProps<T>,
  ref: React.ForwardedRef<TextInput>
) {
  const { name, control, rules, ...inputProps } = props;

  const { field, fieldState } = useController({ control, name, rules });
  return (
    <Input
      ref={ref}
      autoCapitalize="none"
      onChangeText={field.onChange}
      value={field.value as string}
      {...inputProps}
      error={fieldState.error?.message}
    />
  );
}
export const ControlledInput = React.forwardRef(NControlledInput);
```

let me know if this solution work for you

**Comment by NadeemKhanFh** [comment]
thank you so much @yjose for your help. Its working.
