### ISSUE TITLE
How to upgrade template

### ISSUE THREAD

**Issue by kabeza** [obytes/react-native-template-obytes#13]
Hi
I've started the template by doing (as suggested)
`npx react-native init MyApp --template https://github.com/obytes/react-native-template-obytes`

With the latest release published recently
[1.5.1 Release](https://github.com/obytes/react-native-template-obytes/releases/tag/v1.5.1)

How could I update my project with the latest changes? Of course git pull, git fetch won't work because I didn't clone the repository

Thanks

**Comment by yjose** [comment]
👋  @kabeza 
unfortunately,  we can't support upgrading to a new template version automatically as even upgrading to a new RN native require manual tasks, i would suggest checking the release section to see all changed files. 
https://github.com/obytes/react-native-template-obytes/compare/v1.5.0...v1.5.1
