### ISSUE TITLE
white status bar on android release

### ISSUE THREAD

**Issue by iamhaaamed** [obytes/react-native-template-obytes#141]
# Summary:

Status bar color is white on apk release but it has no problem on development.

**Comment by yjose** [comment]
Hey @iamhaaamed, can you provide more details on the issue please, i am not sure how i can help in this case. 
Probably using [StatusBar](https://docs.expo.dev/versions/latest/sdk/status-bar/)  component explicitly inside you screen can fix your issue

**Comment by iamhaaamed** [comment]
Hello @yjose , StatusBar fixes the white color issue but the problem is that the header interferes with the status bar.

**Comment by yjose** [comment]
Header from `react-navigation` correct ?

**Comment by iamhaaamed** [comment]
Yes

**Comment by yjose** [comment]
Not sure if did you [check this guide](https://reactnavigation.org/docs/status-bar/)  from `react-navigation` docs, probably can help you fix the issue. 

@iamhaaamed  Any way look like the problem has nothing to do with the template and related to `react-navigation`
