### ISSUE TITLE
Not able to build to device

### ISSUE THREAD

**Issue by ejkkan** [obytes/react-native-template-obytes#146]
# Summary:
Follwing the steps from the docs and trying to build to my connected device following [this](https://starter.obytes.com/docs/getting-started/create-new-app#running-the-app)

When trying to build it only runs it on a simulator. And when I try to scan the barcode on my device it just says: "No usable data was found". 
Am I missing some steps?

## Steps to reproduce:
-Run new project
-install all dependencies
-connect phone to computer, connec them to the same network
-run yarn ios
- scan barcode

## Expected behavior:
Should be able to install app on device

#### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by citixenken** [comment]
Experiencing the same issue here...

**Comment by alecdewitz** [comment]
run `npx expo run:ios -d <device name>`

**OR**

add a new script in package.json:
`"iphone": "expo run:ios --device iPhone"`
run `pnpm iphone`
