### ISSUE TITLE
Zustand shallow

### ISSUE THREAD

**Issue by RadouaneEzzaggab** [obytes/react-native-template-obytes#163]
# Summary:

Hi guys, i am wondering why you didn't use zustand shallow for getting state in your custom selector.
Pleas can you explain to us why.

**Comment by yjose** [comment]
Hey @RadouaneEzzaggab, we are using the [autogenerated selectors](https://docs.pmnd.rs/zustand/guides/auto-generating-selectors) recommended by the documentation.

I would love to hear more ideas about your approach and why it's better. But it would be great if you could create it as [discussions](https://github.com/obytes/react-native-template-obytes/discussions/categories/q-a).

**Comment by RadouaneEzzaggab** [comment]
Thanks for your reply @yjose, I taked a look to recommended selector i appreciate the way, but i think we have to put shallow for ensure performance no ?
Here is the example from the doc located in github:

<img width="1361" alt="Screenshot 2023-05-15 at 12 08 14" src="https://github.com/obytes/react-native-template-obytes/assets/77213796/fdaf56cd-de9f-48ad-9dc0-564f448f2af0">

**Comment by RadouaneEzzaggab** [comment]
Thanks for your reply @yjose, I taked a look to recommended selector i appreciate the way, but i think we have to put shallow for ensure performance no ?
Here is the example from the doc located in github : https://github.com/pmndrs/zustand

![Screenshot 2023-05-17 at 15 06 55](https://github.com/obytes/react-native-template-obytes/assets/77213796/56f9fa20-e642-419c-96b8-a3630fdb244d)

**Comment by yjose** [comment]
The approach we are using will create atomic stats picks for every state in our store, which means we don't need to add shallow in this case.  here is the source from the docs : 
> It detects changes with strict-equality (old === new) by default, this is efficient for atomic state picks.

If you want to construct objects or arrays, you need to use shallow for performance in this case; however, this is not the case for our situation.

Let me know if you still have more concerns.

**Comment by yjose** [comment]
Sure, please let us know if you have any suggestions on how we can make it better. You can add more ideas in the [Discussion section](https://github.com/obytes/react-native-template-obytes/discussions/categories/ideas).
