### ISSUE TITLE
wrong layout direction while the app language is deferent than local

### ISSUE THREAD

**Issue by hamzamekk** [obytes/react-native-template-obytes#176]
# Summary:
when the phone is in Arabic the layout is RTL

## Steps to reproduce:
set your local to any Arabic country and the template will always be RTL despite the app being English 

## Expected behavior:
the app must be LTR layout

#### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by b0iq** [comment]
+1
