### ISSUE TITLE
App build fails 

### ISSUE THREAD

**Issue by YashJain2409** [obytes/react-native-template-obytes#182]
# Summary:
Every time the app build fails for the first time but after reloading few times it works.

![err](https://github.com/obytes/react-native-template-obytes/assets/60182679/5727cba8-b6ea-49b6-8876-10504d9a2889)

## Steps to reproduce:
pnpm android
press a

#### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by yjose** [comment]
@YashJain2409 Are there any errors in the terminal?

**Comment by YashJain2409** [comment]
Gradle detected a problem with the following location: 'F:\litwiz\floralmarket-b2c-app\android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:compileDebugShaders' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build.
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':expo', ':expo-modules-core'

These were logged in terminal during build process

**Comment by YashJain2409** [comment]
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
It also logged this line as well in terminal

**Comment by yjose** [comment]
Unfortunately, I can't reproduce the issue in my case, but it looks like the issue is related to a Kotlin version mismatch. Please try the fix mentioned in [this issue](https://github.com/software-mansion/react-native-gesture-handler/issues/2307#issuecomment-1430379785).
