### ISSUE TITLE
'EXPO_NO_DOTENV' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by alexIslander** [obytes/react-native-template-obytes#187]
# Summary: 
Can not start example base project. None of the scripts working, which starts with a variable like APP_ENV, EXPO_NO_DOTENV, etc.

`D:\Workspace\js\2023\test-obytes>pnpm android

> test-obytes@0.0.1 android D:\Workspace\js\2023\test-obytes
> EXPO_NO_DOTENV=1 expo run:android

'EXPO_NO_DOTENV' is not recognized as an internal or external command,
operable program or batch file.
 ELIFECYCLE  Command failed with exit code 1.`

## Steps to reproduce: 
I followed the [Create new app guide](https://starter.obytes.com/docs/getting-started/create-new-app) and ran into the issue.

## Expected behavior: 
The project runs on android device.

## Additional notes:
I'm running this project in vscode on Windows.
nvm 1.1.10
node v18.16.1
pnpm v8.6.11

It looks like an environment issue, but don't know in which direction to go. 
It would be really appreciated some help.
Kindly suggest!

**Comment by yjose** [comment]
Hey @alexIslander, can you please install [cross-env](https://www.npmjs.com/package/cross-env#installation) and add it as a prefix for your script? It seems that setting inline environment variables didn't work the same way on Windows.

Please try this fix and let me know if it's working for you, so I can send a solution.

**Comment by liujianchao1995** [comment]
同样的问题

**Comment by yjose** [comment]
@alexIslander, you do have a problem with the package name. Please check your `env.js` file and ensure that the package name is valid.

**Comment by alexIslander** [comment]
Thank you all, for the help and the provided fix!
