### ISSUE TITLE
new app run error

### ISSUE THREAD

**Issue by Justice112** [obytes/react-native-template-obytes#189]
› Building app...
Configuration on demand is an incubating feature.
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open './assets/icon.png'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './assets/icon.png',
  methodName: 'constructor'
}

FAILURE: Build failed with an exception.

**Comment by yjose** [comment]
Hey @Justice112, thank you for reporting this issue. 
Can you confirm that this error is not breaking the Android build for your case? I just tried the new app, and the error appeared, but the build completed successfully.

**Comment by yjose** [comment]
https://github.com/obytes/app-icon-badge/issues/25

**Comment by 0x10Ayoub** [comment]
hey @Justice112 you can solve this issue by adding code below  in ./app.config.ts  
```
  icon: path.resolve(__dirname, './assets/icon.png'),
```
