### ISSUE TITLE
Console Warning, Require cycle: src\navigation\index.tsx -> src\navigation\root-navigator.tsx -> src\screens\index.tsx -> src\screens\onboarding\index.tsx -> src\screens\onboarding\onboarding.tsx -> src\navigation\index.tsx

### ISSUE THREAD

**Issue by theknr** [obytes/react-native-template-obytes#194]
# Summary:

Just pulled down the latest version: npx create-obytes-app@latest MyApp

Now when I run pnpm android I get the below error immediately:

Require cycle: src\navigation\index.tsx -> src\navigation\root-navigator.tsx -> src\screens\index.tsx -> src\screens\onboarding\index.tsx -> src\screens\onboarding\onboarding.tsx -> src\navigation\index.tsx

## Steps to reproduce:

Running on Windows 10
npx create-obytes-app@latest MyApp
code .
pnpm android

## Expected behavior:
Run the app without issues and warnings

**Comment by yjose** [comment]
Thank you, @theknr, for reporting this issue. The issue has been fixed. Please check the [Fix PR](https://github.com/obytes/react-native-template-obytes/pull/195) if you would like to apply it to your project.
