### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by AuYuHui** [obytes/react-native-template-obytes#199]
# Summary:

## Steps to reproduce:
Node.js v18.14.0

## Additional notes:
![image](https://github.com/obytes/react-native-template-obytes/assets/38815121/f38110e2-9601-4597-97cb-3a9198a6103a)
![image](https://github.com/obytes/react-native-template-obytes/assets/38815121/8697ec72-83e1-4903-865d-ae85a386df2d)

#### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by 0x10Ayoub** [comment]
hey @AuYuHui  can you add execution permission `chmod +x eas-pre-install`

**Comment by electr0de** [comment]
> hey @AuYuHui can you add execution permission `chmod +x eas-pre-install`

If the script is executing in the cloud, how could one grant it permission to execute on that system?

**Comment by 0x10Ayoub** [comment]
it should works  because you just adding execution permission to the file .

> > hey @AuYuHui can you add execution permission `chmod +x eas-pre-install`
> 
> If the script is executing in the cloud, how could one grant it permission to execute on that system?

**Comment by electr0de** [comment]
Yeah that's probably right. Although I did try to give it permission using wsl, but in windows, it kept on giving me the same error. Although the eas-build on wsl itself was working fine. I guess to build, use wsl?

**Comment by 0x10Ayoub** [comment]
yes , because permission file in windows is different from Linux/Unix/

**Comment by Blqckcore** [comment]
> Yeah that's probably right. Although I did try to give it permission using wsl, but in windows, it kept on giving me the same error. Although the eas-build on wsl itself was working fine. I guess to build, use wsl?

How did you perform the build on wsl?

**Comment by electr0de** [comment]
> > Yeah that's probably right. Although I did try to give it permission using wsl, but in windows, it kept on giving me the same error. Although the eas-build on wsl itself was working fine. I guess to build, use wsl?
> 
> How did you perform the build on wsl?

Eas local build
