### ISSUE TITLE
How is the workflow when compiling the app with `react-native-version`?

### ISSUE THREAD

**Issue by Pkcarreno** [obytes/react-native-template-obytes#20]
Hi!,

I have been seeing in the CI/CD guides that `np` is used in conjunction with `react-native-version`, in the guide it uses `np` but there is no mention of `react-native-version` afterwards, I don't get much information for the use of these two libraries together, it would help me if you could explain how these two work together

Thanks

**Comment by yjose** [comment]
@Pkcarreno  check this guide here https://www.obytes.com/blog/react-native-github-action

**Comment by Pkcarreno** [comment]
Sorry for opening the thread, I didn't know that `npm version` also runs the `postversion` command

Thanks a lot
