### ISSUE TITLE
project fails to run

### ISSUE THREAD

**Issue by LRboyz** [obytes/react-native-template-obytes#210]
# Summary:

## I cloned the latest code of the warehouse and followed the tutorials in the document to operate in sequence, but in the end it did not run successfully. The error message is as follows. What is the problem?
![img_v2_8c3acecf-2530-41da-8cd7-3ab59f7bd0ag](https://github.com/obytes/react-native-template-obytes/assets/48092353/4af3c4d9-9893-4bc1-b343-8354a8bd7536)

#### Tasks

- [ ] fix bug
- [ ] test
- [ ] release

**Comment by LESANF** [comment]
check your react-native, expo and virtual device
