### ISSUE TITLE
Java Error - No idea

### ISSUE THREAD

**Issue by LansPeti** [obytes/react-native-template-obytes#220]
# Summary:
I followed the exact steps, now after pnpm android, the emulator starts and while the app is starting I get this error.
## Steps to reproduce:
Start everything on a new computer and try to start pnpm android
## Expected behavior:
The app should start and show me the simple expo app.
## Additional notes:
![image](https://github.com/obytes/react-native-template-obytes/assets/65248100/5e3c7e79-b5b9-4f44-855c-828e72bce1a1)
I downloaded Java 8 and 11 now I'm just going crazy because I'm doing all these Android Simulator things now for 3 hours
#### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by Rvey** [comment]
I'm also facing the same issue. Any workarounds?

**Comment by Rvey** [comment]
@LansPeti  I have figured out a solution. Simply ensure that you have JDK 11 installed. You can download it from here: [https://www.oracle.com/java/technologies/javase/jdk11-archive-downloads.html](https://www.oracle.com/java/technologies/javase/jdk11-archive-downloads.html)

Alternatively, you can follow these instructions: [https://reactnative.dev/docs/environment-setup?guide=native](https://reactnative.dev/docs/environment-setup?guide=native)

cheers

**Comment by LansPeti** [comment]
@Rvey thanks, I will try this out
