### ISSUE TITLE
Screens without bottomtabbar

### ISSUE THREAD

**Issue by duard** [obytes/react-native-template-obytes#222]
# Summary:
I cant figure out how to create 1, 2, 3 screens that do not show bottom tabbar

## Steps to reproduce:
clone the project
## Expected behavior:
An screen routed that do not show the bottom tabbar
#### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by yjose** [comment]
@Edward, the template comes with a simple routes demo. If you want more details, make sure to check the [React Navigation documentation](https://reactnavigation.org/docs/nesting-navigators).
