### ISSUE TITLE
import web3 "ReferenceError: Property 'EventTarget' doesn't exist, js engine: hermes"

### ISSUE THREAD

**Issue by xianxianzhou** [obytes/react-native-template-obytes#227]
# Summary:
web3 init error,
ERROR  ReferenceError: Property 'EventTarget' doesn't exist, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:

## Steps to reproduce:
  "dependencies": {
    "@react-navigation/bottom-tabs": "^6.5.9",
    "@react-navigation/native": "^6.1.8",
    "@react-navigation/native-stack": "^6.9.14",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-safe-area-context": "^4.7.3",
    "react-native-screens": "^3.26.0",
    "web3": "^1.7.1"

  },
## Expected behavior:
import Web3 from 'web3';
const web3 = new Web3();
web3.setProvider(new web3.providers.HttpProvider('https://mainnet.infura.io/v3/5209c849762f40ce866e3b1332596997'));
#### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by yjose** [comment]
Hey @xianxianzhou, Apparently, this issue is not related to the template. please check [this issue ](https://github.com/web3/web3.js/issues/6253)
