### ISSUE TITLE
eas build wont work with template

### ISSUE THREAD

**Issue by morty052** [obytes/react-native-template-obytes#233]
# Summary:
eas build exits at pre install phase
![Screenshot 2023-11-01 013719](https://github.com/obytes/react-native-template-obytes/assets/141450145/82bb9715-76b1-45ef-ac85-b434d74f8f4d)

## Steps to reproduce:
pnpm build:development:android

**Comment by Blqckcore** [comment]
Did you fix this?

**Comment by yjose** [comment]
the pre build script has been deleted in the last version, so its should work now without issues

**Comment by Blqckcore** [comment]
> the pre build script has been deleted in the last version, so its should work now without issues

FYI: Some docs pages are not displayed correctly now, e.g. https://starter.obytes.com/guides/data-fetching/ or https://starter.obytes.com/guides/navigation/

**Comment by yjose** [comment]
Yeah thank you 🙏, fixed
