### ISSUE TITLE
EAS Build gives error for iOS 

### ISSUE THREAD

**Issue by bubabi** [obytes/react-native-template-obytes#235]
# Summary:
<img width="1247" alt="Screenshot 2023-11-05 at 11 03 31 PM" src="https://github.com/obytes/react-native-template-obytes/assets/23321849/d4495d3f-d545-480e-870c-4a7f3ddbb30f">

## Steps to reproduce:
Run `eas build -p ios --profile simulator` in your terminal.

**Comment by rishiE404** [comment]
> # Summary:
> <img alt="Screenshot 2023-11-05 at 11 03 31 PM" width="1247" src="https://user-images.githubusercontent.com/23321849/280557605-d4495d3f-d545-480e-870c-4a7f3ddbb30f.png">
> ## Steps to reproduce:
> Run `eas build -p ios --profile simulator` in your terminal.

Hey @bubabi Can you please confirm that you have installed the correct version of pnpm? Also if you can share the detailed logs from install custom hooks command.

**Comment by kendo-leadlab** [comment]
i am having the same issue: seems that you cant run the preintall the install pnmp on expo
an idea on how to solve this?


Script 'eas-build-pre-install' is present in package.json, running it...
> protein2@0.0.1 eas-build-pre-install /home/expo/workingdir/build
> ./scripts/eas-pre-install
sh: 1:
./scripts/eas-pre-install: Permission denied
ELIFECYCLE  Command failed with exit code 126.



pnpm run eas-build-pre-install exited with non-zero code: 1

**Comment by yjose** [comment]
@bubabi @kendo-leadlab Apparently, EAS now supports installing pnpm without a pre-hook. So, you can delete `eas-build-pre-install` from your `package.json` scripts and set the pnpm version in your EAS config. [Check the docs](https://docs.expo.dev/eas/json/#pnpm).

**Comment by Blqckcore** [comment]
> @bubabi @kendo-leadlab Apparently, EAS now supports installing pnpm without a pre-hook. So, you can delete `eas-build-pre-install` from your `package.json` scripts and set the pnpm version in your EAS config. [Check the docs](https://docs.expo.dev/eas/json/#pnpm).

Hey, can you please further explain the adjustments of the eas.json?

**Comment by wahidshadab** [comment]
+1
