### ISSUE TITLE
... Only alphanumeric characters, '.' and '_' are allowed, and each '.' must be followed by a letter...

### ISSUE THREAD

**Issue by onurusluca** [obytes/react-native-template-obytes#239]
# Summary:

```
❯ pnpm android

> obytesapp@0.0.1 android C:\CODING\LEARNING\MOBILE APPS\ObytesApp
> cross-env EXPO_NO_DOTENV=1 expo run:android

AssertionError [ERR_ASSERTION]: Invalid format of Android package name. Only alphanumeric characters, '.' and '_' are allowed, and each '.' must be followed by a letter.
 ELIFECYCLE  Command failed with exit code 1.
```

## Steps to reproduce:

1. run `npx create-obytes-app@latest MyApp`
2. cd into project
3. run `pnpm android`
4. error

## Expected behavior:
Dev server should start

## Additional notes:
I have other react-native-cli, expo and android app dev environments working fine.

## System Info:
```
System
  platform           win32
  arch               x64
  cpu                12 cores       AMD Ryzen 5 5600X 6-Core Processor
  directory          yolda-client   C:\CODING\LEARNING\MOBILE APPS\yolda-client

JavaScript (and globally-installed packages)
  node               19.0.0        C:\Program Files\nodejs\node.EXE
  npm                9.6.2          C:\Program Files\nodejs\npm.CMD
  eas-cli          5.6.0
  nodemon          2.0.22
  npm              9.6.2
  pnpm             8.9.2
  tile-extruder    2.1.0
  typescript       5.1.3
  yarn               -      not installed
  pnpm               8.9.2            C:\Users\dur2d\AppData\Local\pnpm\pnpm.EXE     <no pnpm global package info available>
  expo               48.0.21 -> .\node_modules\.pnpm\expo@48.0.21_@babel+core@7.23.3\node_modules\expo   managed

Android
  java               21.0.1       C:\Program Files\Common Files\Oracle\Java\javapath\java.EXE
  android home       -            C:\Users\dur2d\AppData\Local\Android\Sdk

Tools
  git                git version 2.42.0.windows.2   C:\Program Files\Git\cmd\git.EXE
```

**Comment by onurusluca** [comment]
Of course 5 seconds after I wrote an issue I found the culprit. 

env.js:
```
...
const BUNDLE_ID = 'com.expo-ownerapp'; // ios bundle id
const PACKAGE = 'com.expo-ownerapp'; // android package name
...
```

Removing the hyphens(-), solved the issue. 

Why is this happening?

**Comment by SihamBen** [comment]
Hello @onurusluca,
as the error suggests you are not allowed to use hyphens in package name, this is a result of the naming convention in android 
```js
//taken from android docs

the naming rules for the application ID are a bit more restrictive:

- It must have at least two segments (one or more dots).
- Each segment must start with a letter.
- All characters must be alphanumeric or an underscore [a-zA-Z0-9_].
```

**Comment by onurusluca** [comment]
@SihamBen Thanks for the reply.

That's the thing though, I've started the CLI with the name `MyApp` but it still did give me error. I think the configuration is at fault here? It took the name I've given it and created the below code which breakers the app:
...
const BUNDLE_ID = 'com.expo-ownerapp'; // ios bundle id
const PACKAGE = 'com.expo-ownerapp'; // android package name
...


Also shouldn't we put that in the docs? I am willing to open a PR for it if that's okay?

**Comment by SihamBen** [comment]
I'm actually confused why this happen on your side, because I've just followed the same steps and default values are 
```
const BUNDLE_ID = 'com.myapp'; // ios bundle id
const PACKAGE = 'com.myapp'; // android package name
```
For the docs, sure feel free to open a PR

**Comment by onurusluca** [comment]
That's weird. So, on my end the CLI add 'expo' to the package name? I don't know what to do but I will just leave it here for anyone to see. 
Also making a PR for the clarification of naming.

**Comment by thomas-klein** [comment]
Hello there !
First time using Obytes Starter here and I had the same issue.
I installed using : `npx create-obytes-app@latest TestObytes`
Tried to launch android emulator with `pnpm android` 
Got the error described by OP and thanks to previous answers found the cause in `TestObytes/env.js` :
```js
const BUNDLE_ID = 'com.testexpo-owner'; // ios bundle id
const PACKAGE = 'com.testexpo-owner'; // android package name
const NAME = 'Testexpo-owner'; // app name
const EXPO_ACCOUNT_OWNER = 'expo-owner'; // expo account owner
const SCHEME = 'Testexpo-owner'; // app scheme
```
