### ISSUE TITLE
Build filed- Task :expo-modules-core:configureCMakeDebug[arm64-v8a] FAILED

### ISSUE THREAD

**Issue by dangzhiyuan** [obytes/react-native-template-obytes#251]
# Summary:
I followed the document step by step，and always fails after executing command pnpm android.
![qwe](https://github.com/obytes/react-native-template-obytes/assets/80813444/c53bfb7a-5a10-4050-9abf-4e9646e2e7c0)

## Steps to reproduce:
pnpm android failed
## Additional notes:
node:18.17.0
gradle:8.0.1
javac:11.0.21
android SDK:33
#### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by electr0de** [comment]
What's your pnpm version? I suggest sticking to 8.6.5 as updates can be breaking.
