### ISSUE TITLE
Assets are missing after EAS Build

### ISSUE THREAD

**Issue by tonven** [obytes/react-native-template-obytes#253]
I added some assets in an assets subfolder (assets/images/onboarding/onboarding_1.png) and loaded them in a code like this: 
`const [assets] = useAssets(
    require('myapp/assets/images/onboarding/onboarding_1.png')
  );
`
on emulator everything works fine, but it does not work during eas build. Images are not there. 
Am I missing some configuration?

Thank you!

**Comment by yjose** [comment]
No i dont think there is any config for that. Probbaly it's just a build issue. any way this issue should be related to EAS and has nothing to do with the template. 

will close it for now
