### ISSUE TITLE
local build must be of same type as eas build to publish

### ISSUE THREAD

**Issue by ejkkan** [obytes/react-native-template-obytes#257]
# Summary:
See title

## Steps to reproduce:
1. prebuild local build to production
2. publish a production build to eas. wait for it to finish
3. now run a local prebuild to development
4. run eas submit --platform ios and pick the production build
5. It pick the build "com.yourapp.development" to publish and in my case fail
6. run a production prebuild 
7. run submit command and now it works

## Expected behavior:
1. prebuild local build to production
2. publish a production build to eas. wait for it to finish
3. now run a local prebuild to development
4. run eas submit --platform ios and pick the production build
5. successful deploy

**Comment by yjose** [comment]
I see, I think this is a normal behavior as we use prebuild as a way to create multiple app variants for the app (dev/staging/prod) normally you should run prebuild for production before trying to submit the production build. 

I do not have any idea how we can make it work without rebuilding, to be honest as EAS Submit will use the bundle id  used in the native folder. So, technically, you should rebuild to use the production one.
