### ISSUE TITLE
react-native-mmkv is not supported in Expo Go! Use EAS (expoprebuild') or eject to a bare workflow instead.

### ISSUE THREAD

**Issue by coderDancer** [obytes/react-native-template-obytes#264]
# Summary:

## Steps to reproduce:
pnpm start
switch to Expo Go

## Expected behavior:
no Error

#### Tasks

- [ ] pnpm start
- [ ] Press s │ switch to Expo Go

![5cd2d9a4f9c8b946ba39a0f3d7599fb](https://github.com/obytes/react-native-template-obytes/assets/22238447/539c5f9e-7162-40ad-b531-210d0b177db1)

**Comment by 0x10Ayoub** [comment]
@coderDancer you need to run this commands in order
-  `npm prebuild`  to generate iOS and Android you can read more about it here https://docs.expo.dev/workflow/prebuild/
- `pnpm ios` or `pnpm android` to build the app check package.json for more details and this https://docs.expo.dev/workflow/customizing/

**Comment by coderDancer** [comment]
I'm still having trouble.
Could you please provide more detailed instructions?
I want to run a project locally using Expo Go. 
Thank you

**Comment by coderDancer** [comment]
I'm still having trouble.
Could you please provide more detailed instructions?
I want to run a project locally using Expo Go.
Thank you

> @coderDancer you need to run this commands in order
> 
> * `npm prebuild`  to generate iOS and Android you can read more about it here https://docs.expo.dev/workflow/prebuild/
> * `pnpm ios` or `pnpm android` to build the app check package.json for more details and this https://docs.expo.dev/workflow/customizing/

I'm still having trouble.
Could you please provide more detailed instructions?
I want to run a project locally using Expo Go.
Thank you

**Comment by 0x10Ayoub** [comment]
@coderDancer  you need to connect your mobile with a cable to build the app in your phone 
it will not work if you scan the app with default expo  app

**Comment by coderDancer** [comment]
> @coderDancer you need to connect your mobile with a cable to build the app in your phone您需要使用数据线连接手机才能在手机中构建应用程序 it will not work if you scan the app with default expo app如果您使用默认的 Expo 应用程序扫描应用程序，它将不起作用

Can I use a simulator as well?

**Comment by 0x10Ayoub** [comment]
yes you can 

> > @coderDancer you need to connect your mobile with a cable to build the app in your phone您需要使用数据线连接手机才能在手机中构建应用程序 it will not work if you scan the app with default expo app如果您使用默认的 Expo 应用程序扫描应用程序，它将不起作用
> 
> Can I use a simulator as well?
