### ISSUE TITLE
Add Tamagui an optional UI kit

### ISSUE THREAD

**Issue by Byevenes** [obytes/react-native-template-obytes#286]
# Summary: I think this template is really good to incorporate tamagui x styles && ui kit

**Comment by yjose** [comment]
Hey @Byevenes, thank you for the recommendation 
Right now, we are not providing multiple choices for the same thing. If you read our philosophy, the starter reflects exactly what we are using internally, which we believe is the best choice for our use case and, mostly, for most cases when building a mobile app with react native. We didn't try Tamagui to be honest here, and we are not planning to include it in the repository, at least for now.

Providing multiple choices will make the repository hard to maintain, as we have limited time for it.

With that being said, integrating Tamagui is not that hard if you want to make it work for your use case. You can start a new project with Obytes Starter and update the UI from Tailwind CSS to Tamagui, while still benefiting from other features.

**Comment by Byevenes** [comment]
I really appreciate for the quick response and reply with honest thinking thank you 🫶🏽🤍
