### ISSUE TITLE
Web build is not working

### ISSUE THREAD

**Issue by tonven** [obytes/react-native-template-obytes#289]
# Summary:
Running` npx expo start --web` is not working. It stucks infinitely. Android builds and runs perfectly.
## Steps to reproduce:

1. Install last version of template (5.2.0)
2. `pnpm install`
3. `cross-env EXPO_NO_DOTENV=1 npx expo start --web`

## Expected behavior:
Web is working
## Additional notes:
Windows OS.
I tried to copy changes made here: #287, but it does not fix the issue.

**Comment by dmitryshostak** [comment]
This is the changeset you're looking for to fix the build. https://github.com/marklawlor/nativewind/pull/860
