### ISSUE TITLE
using Expo AuthSession

### ISSUE THREAD

**Issue by hazimal** [obytes/react-native-template-obytes#291]
hello @everyone 
thank you for this template it is really nice startkit 
how do i can using Expo AuthSession with this template
and how to config app with-in 
thanks

**Comment by yjose** [comment]
Hey @hazimal , The template has nothing special to use Expo AuthSessions or any other library.  You can refer to the [Expo AuthSession documentation](https://docs.expo.dev/versions/latest/sdk/auth-session/) for guidance and the library should work without any issues

**Comment by hazimal** [comment]
@yjose thank you
