### ISSUE TITLE
Env Build Time

### ISSUE THREAD

**Issue by hazimal** [obytes/react-native-template-obytes#295]
# Summary:
Running "pnpm android" is not working.
## Steps to reproduce:
installing Facebook react-native-fbsdk-next and config plugin with 
`[
      'react-native-fbsdk-next',

      {
        appID: Env.FACEBOOK_APP_ID,
        clientToken: Env.FACEBOOK_APP_SECRET,
        displayName: 'MyApp',
        advertiserIDCollectionEnabled: true,
        autoLogAppEventsEnabled: true,
        isAutoInitEnabled: true,
        iosUserTrackingPermission:
          'This identifier will be used to deliver personalized ads to you.',
      },
    `],``
## Expected behavior:
Building app...
Configuration on demand is an incubating feature.
/AppDir/node_modules/react-native-fbsdk-next/plugin/build/withFacebook.js:13
        throw new Error('missing appID in the plugin properties');
## Additional notes:
it stop working unexpectedly
#### Tasks
when i change Env.FACEBOOK_APP_ID to "My Facebook App Id" it working 

i was setup my Env.FACEBOOK_APP_ID build time not in client Env
`npx cross-env EXPO_NO_CLIENT_ENV_VARS=1 expo run:android`

**Comment by yjose** [comment]
Can you run prebuild after you change your env vars

**Comment by hazimal** [comment]
yes pnpm prebuild
same result

**Comment by hazimal** [comment]
yes please 
`/*
 * Env file to load and validate env variables
 * Be cautious; this file should not be imported into your source folder.
 * We split the env variables into two parts:
 * 1. Client variables: These variables are used in the client-side code (src folder).
 * 2. Build-time variables: These variables are used in the build process (app.config.ts file).
 * Import this file into the `app.config.ts` file to use environment variables during the build process. The client variables can then be passed to the client-side using the extra field in the `app.config.ts` file.
 * To access the client environment variables in your `src` folder, you can import them from `@env`. For example: `import Env from '@env'`.
 */
/**
 * 1st part: Import packages and Load your env variables
 * we use dotenv to load the correct variables from the .env file based on the APP_ENV variable (default is development)
 * APP_ENV is passed as an inline variable while executing the command, for example: APP_ENV=staging pnpm build:android
 */
const z = require('zod');

const packageJSON = require('./package.json');
const path = require('path');
const APP_ENV = process.env.APP_ENV ?? 'development';
const envPath = path.resolve(__dirname, `.env.${APP_ENV}`);

require('dotenv').config({
  path: envPath,
});

/**
 * 2nd part: Define some static variables for the app
 * Such as: bundle id, package name, app name.
 *
 * You can add them to the .env file but we think it's better to keep them here as as we use prefix to generate this values based on the APP_ENV
 * for example: if the APP_ENV is staging, the bundle id will be com.obytes.staging
 */

// TODO: Replace these values with your own

const BUNDLE_ID = 'com.my-app'; // ios bundle id
const PACKAGE = 'com.my-app'; // android package name
const NAME = 'MyApp'; // app name
const EXPO_ACCOUNT_OWNER = 'userAccount'; // expo account owner
const EAS_PROJECT_ID = 'My Id'; // eas project id
const SCHEME = 'myApp'; // app scheme

/**
 * We declare a function withEnvSuffix that will add a suffix to the variable name based on the APP_ENV
 * Add a suffix to variable env based on APP_ENV
 * @param {string} name
 * @returns  {string}
 */

const withEnvSuffix = (name) => {
  return APP_ENV === 'production' ? name : `${name}.${APP_ENV}`;
};

/**
 * 2nd part: Define your env variables schema
 * we use zod to define our env variables schema
 *
 * we split the env variables into two parts:
 *    1. client: These variables are used in the client-side code (`src` folder).
 *    2. buildTime: These variables are used in the build process (app.config.ts file). You can think of them as server-side variables.
 *
 * Main rules:
 *    1. If you need your variable on the client-side, you should add it to the client schema; otherwise, you should add it to the buildTime schema.
 *    2. Whenever you want to add a new variable, you should add it to the correct schema based on the previous rule, then you should add it to the corresponding object (_clientEnv or _buildTimeEnv).
 *
 * Note: `z.string()` means that the variable exists and can be an empty string, but not `undefined`.
 * If you want to make the variable required, you should use `z.string().min(1)` instead.
 * Read more about zod here: https://zod.dev/?id=strings
 *
 */

const client = z.object({
  APP_ENV: z.enum(['development', 'staging', 'production']),
  NAME: z.string(),
  SCHEME: z.string(),
  BUNDLE_ID: z.string(),
  PACKAGE: z.string(),
  VERSION: z.string(),

  // ADD YOUR CLIENT ENV VARS HERE
  API_URL: z.string(),
  API_PRODUCT_URL: z.string(),
  API_KEY: z.string(),
  SUPABASEURL: z.string(),
  SUPABASEANONKEY: z.string(),
  SUPABASENAME: z.string(),
  GOOGLECLIENTID: z.string(),
});

const buildTime = z.object({
  EXPO_ACCOUNT_OWNER: z.string(),
  EAS_PROJECT_ID: z.string(),
  // ADD YOUR BUILD TIME ENV VARS HERE
  SECRET_KEY: z.string(),
  FACEBOOK_APP_ID: z.string(),
  FACEBOOK_APP_SECRET: z.string(),
  FACEBOOK_APP_VERSION: z.string(),
});

/**
 * @type {Record<keyof z.infer<typeof client> , string | undefined>}
 */
const _clientEnv = {
  APP_ENV,
  NAME: NAME,
  SCHEME: SCHEME,
  BUNDLE_ID: withEnvSuffix(BUNDLE_ID),
  PACKAGE: withEnvSuffix(PACKAGE),
  VERSION: packageJSON.version,

  // ADD YOUR ENV VARS HERE TOO
  API_URL: process.env.API_URL,
  API_PRODUCT_URL: process.env.API_PRODUCT_URL,
  API_KEY: process.env.API_KEY,
  SUPABASEURL: process.env.SUPABASEURL,
  SUPABASEANONKEY: process.env.SUPABASEANONKEY,
  SUPABASENAME: process.env.SUPABASENAME,
  GOOGLECLIENTID: process.env.GOOGLECLIENTID,
};

/**
 * @type {Record<keyof z.infer<typeof buildTime> , string | undefined>}
 */
const _buildTimeEnv = {
  EXPO_ACCOUNT_OWNER,
  EAS_PROJECT_ID,
  // ADD YOUR ENV VARS HERE TOO
  SECRET_KEY: process.env.SECRET_KEY,
  FACEBOOK_APP_ID: process.env.FACEBOOK_APP_ID,
  FACEBOOK_APP_SECRET: process.env.FACEBOOK_APP_SECRET,
  FACEBOOK_APP_VERSION: process.env.FACEBOOK_APP_VERSION,
};

/**
 * 3rd part: Merge and Validate your env variables
 * We use zod to validate our env variables based on the schema we defined above
 * If the validation fails we throw an error and log the error to the console with a detailed message about missed variables
 * If the validation passes we export the merged and parsed env variables to be used in the app.config.ts file as well as a ClientEnv object to be used in the client-side code
 **/
const _env = {
  ..._clientEnv,
  ..._buildTimeEnv,
};

const merged = buildTime.merge(client);
const parsed = merged.safeParse(_env);

if (parsed.success === false) {
  console.error(
    '❌ Invalid environment variables:',
    parsed.error.flatten().fieldErrors,

    `\n❌ Missing variables in .env.${APP_ENV} file, Make sure all required variables are defined in the .env.${APP_ENV} file.`,
    `\n💡 Tip: If you recently updated the .env.${APP_ENV} file and the error still persists, try restarting the server with the -cc flag to clear the cache.`
  );
  throw new Error(
    'Invalid environment variables, Check terminal for more details '
  );
}

const Env = parsed.data;
const ClientEnv = client.parse(_clientEnv);

module.exports = {
  Env,
  ClientEnv,
  withEnvSuffix,
};
`
`API_URL=https://dummyjson.com/
API_PRODUCT_URL=https://userAccount.supabase.co/rest/v1/
GOOGLECLIENTID="GoogleId.apps.googleusercontent.com"
## TOTO: add the variable to your  CI and remove it from here, not recommended setting sensitive values on your git repo
SECRET_KEY=my-secret-key
FACEBOOK_APP_ID="FCID"
FACEBOOK_APP_SECRET="FBSECRET"
FACEBOOK_APP_VERSION="1"
SUPABASENAME=SUPABASENAME
SUPABASEURL="https://Account.supabase.co"
SUPABASEANONKEY="Key"
API_KEY=API_KEY`

**Comment by hazimal** [comment]
it is now working without change any, i don't know why 
thanks you @yjose
