### ISSUE TITLE
App generation not proper

### ISSUE THREAD

**Issue by preetb123** [obytes/react-native-template-obytes#3]
Executing `npx react-native init MyApp --template https://github.com/obytes/react-native-template-obytes` only clones the template and not actually generating a react native project. `src` folder is not added
<img width="841" alt="Screenshot 2021-06-25 at 5 10 17 PM" src="https://user-images.githubusercontent.com/4496555/123420093-b5855b00-d5d8-11eb-95e9-e49da16bdc39.png">

**Comment by yjose** [comment]
Hey @preetb123 , this issue should happen if you have an old react-native CLI installed globally , can you please remove it using 
```
npm uninstall -g react-native-cli
```

now you can run 

```
npx react-native init MyApp --template https://github.com/obytes/react-native-template-obytes
```
and should work correctly, please let me know if the issue still persists even after removing global CLI
