### ISSUE TITLE
Failed to create the native directory when running `pnpm android` 

### ISSUE THREAD

**Issue by Oussama-El-Amrani** [obytes/react-native-template-obytes#301]
# Summary:
Cannot create the native directory when running pnpm android
## Steps to reproduce:
- pnpm  android
After running the above command, i get the following error:
```zsh
> cross-env EXPO_NO_DOTENV=1 expo run:android
Could not get npm url for package "expo-template-bare-minimum@sdk-50"
✖ Failed to create the native directory
You may want to delete the ./ios and/or ./android directories before trying again.
```
## Expected behavior:
The Expo CLI should create the native directory and start building the Android app without any errors.
## Additional notes:
I'm using the following versions:
Node.js: v20.12.1
pnpm: 8.15.5

**Comment by Oussama-El-Amrani** [comment]
I have retried many times but cannot fix it. I am using a Linux machine (Ubuntu 22.04), and I have tried it on a Windows VM, where it works without any problems. I will provide an update if I resolve it.

**Comment by yjose** [comment]
@CertainPassenger  @Oussama-El-Amrani  did you check this issue [here](https://stackoverflow.com/questions/71183795/expo-error-while-choosing-template-could-not-get-npm-url-for-package)  apparently is not related to the starter but a common issue with expo templates as you need to install the right node version
