### ISSUE TITLE
Add support for React Native Reusables

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [obytes/react-native-template-obytes#302]
# Summary:
it would be really useful to add support for React Native Reusables which is [shadcn/ui](https://ui.shadcn.com/) for react native

https://rnr-docs.vercel.app/getting-started/introduction/

**Comment by yjose** [comment]
Hello @Ashraf-Ali-aa, thank you for the recommendation. I am personally following the work done by React Native Reusable, and I think it is promising. However, for now, we are providing a set of core components that work for most cases. 

Also, I think it's very easy to add it to the project if you want to, but we are not planning to include it at least in the near future.
