### ISSUE TITLE
adding darkMode : class is breaking UI on mobile.

### ISSUE THREAD

**Issue by MohammadHarisZia** [obytes/react-native-template-obytes#307]
# Summary:
I refactored mmkv and softtouchinput to use expo go app but when I use the latest fix darkmode on web commit it breaks styles on mobile. Specifically Text , settings menu and modal options, I am using the setup from 5.2.0 release and seems like dark: style are applied on mobile despite it being light mode on mobile

Light Theme:

<img width="404" alt="Screenshot 2024-04-17 at 7 31 58 PM" src="https://github.com/obytes/react-native-template-obytes/assets/63912301/d42a1de0-f638-4263-87c5-2f6a0c04208c">

<img width="352" alt="Screenshot 2024-04-17 at 7 48 35 PM" src="https://github.com/obytes/react-native-template-obytes/assets/63912301/ba016933-e6d5-46cf-8d8c-f4fe475d3cfe">

Dark Theme:
<img width="351" alt="Screenshot 2024-04-17 at 7 49 07 PM" src="https://github.com/obytes/react-native-template-obytes/assets/63912301/e67f3863-774a-409e-bce3-60e3bf85fbd0">

<img width="341" alt="Screenshot 2024-04-17 at 7 49 29 PM" src="https://github.com/obytes/react-native-template-obytes/assets/63912301/4d7164af-b95a-4875-9fc1-011aab228d15">

## Steps to reproduce:

From changelog 5.2.0 I used your dark mode support commit to change tailwind config and root layout

#### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by Hessuew** [comment]
I think I'm on the latest version and noticed the same. I just added the theme button from the settings screen to test it in my new home screen and find out every text and button remained white while the background turned white.

Btw thank you for the super great starter/template. I have tested some and I think this is the best. Specifically the workflow + husky section is super nice. Keep up the good work 😄👍💯🥇

**Comment by tlebeitsuk** [comment]
Same here.

**Comment by ElenaBitire** [comment]
What tailwindcss version do you have? In case you have a different version than 3.3.2 (the one we have on the template), then changing the `darkMode: 'class` to `darkMode: 'media'`  in the tailwind.config.js file should solve this issue on mobile, while on web isn't going to work as expected.

**Comment by MohammadHarisZia** [comment]
Hey @ElenaBitire thank you so much for bringing this up! It was the tailwind version issue. For everyone else getting this issue kindly downgrade your tailwind CSS to 3.3.2 from whatever version you are using and you will be good to go using the `darkMode: class` in tailwind config.

**Comment by minhdangoz** [comment]
> What `tailwindcss` version do you have? In case you have a different version than 3.3.2 (the one we have on the template), then changing the `darkMode: 'class'` to `darkMode: 'media'` in the `tailwind.config.js` file should solve this issue on mobile, while on web isn't going to work as expected.

Thanks, it solved my problem

**Comment by Hessuew** [comment]
Yes, ensuring that the version is 3.3.2, not any above, solved the problem for me also.

Thank you very much.
