### ISSUE TITLE
Upgrade SVG package version to 15.3.0

### ISSUE THREAD

**Issue by KingEnjera** [obytes/react-native-template-obytes#323]
# Summary: 

Current version (15.2.0) of svg package produces the following issue: https://github.com/software-mansion/react-native-svg/issues/2241

Note - pnpm --version: 9.3.0

## Steps to reproduce:

Start a new project and run it on an ios simulator.

## Expected behavior:

✔ Installed CocoaPods

## Solution

Just upgrade svg package to 15.3.0

**Comment by ttmottt** [comment]
@KingEnjera , sorry to disrupt you message do you success ton install this template ?  Can i reach you un DM ?
