### ISSUE TITLE
Tailwind/CSS classes are not being applied

### ISSUE THREAD

**Issue by TechNech** [obytes/react-native-template-obytes#331]
# Summary:
Whenever I run the project using ```pnpm ios``` it doesn't seem to load the css. After I did changes saved and ran the project again later.

## Steps to reproduce:
- Run the starter template
- Make changes in styling etc

## Expected behavior:

- You need to manually reload for the terminal for a few times to get it to look like this again.

![Simulator Screenshot - iPhone 15 Pro Max - 2024-06-28 at 08 40 25](https://github.com/obytes/react-native-template-obytes/assets/4355289/c7604b92-6c1f-40ea-81c4-f10212aec96a)

## Additional notes:
<img width="418" alt="Screenshot 2024-06-30 at 4 02 21 AM" src="https://github.com/obytes/react-native-template-obytes/assets/4355289/80f5dbe6-cc2a-409b-ae3a-6d94b5e43581">

**Comment by TechNech** [comment]
Yes, that is also a workaround. I am using `pnpm ios`.

**Comment by 0x1337ak** [comment]
@TechNech  you can use `pnpm start -c`  to clear the cache no need to rebuild

**Comment by BeniSyach** [comment]
I working for use ``pnpm start -c`` thank you @TechNech

**Comment by yjose** [comment]
should be fixed with the last version as we migrate to the last nativewind version
