### ISSUE TITLE
supabase support 

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [obytes/react-native-template-obytes#346]
it would be really good to see supabase support as a backend, since it supports authentication, API, and storage. One more added benefit is it would help transition to local first app https://localfirstweb.dev/ using tools like tinybase

**Comment by yjose** [comment]
Thanks @Ashraf-Ali-aa for your suggestion, but unfortunately we can't include all solutions out there. Our goal is to provide a solid foundation for React Native projects, and it's up to people to add what they want.
