### ISSUE TITLE
error : JAVA_HOME is not set and no 'java' command could be found in your PATH.

### ISSUE THREAD

**Issue by ThiMaul** [obytes/react-native-template-obytes#373]
# Summary:
Hello,
I just start with react naive and I want to use your template to start it good. I'm on windows 11 and I have an virtual device started with Android Studio. I follow thoses few steps and the error appear :

## Steps to reproduce:
- npm install -g pnpm (all good)
- npx create-obytes-app@latest MyApp (all good)
- cd MyApp (all good)
- pnpm android (error)

## Expected behavior:
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

## Additional notes:
I try to download OpenJDK but the last version dont match with the parameters inside the apps. So I look mode deeply to your app and it seem's it should automatically install JDK (like seen here : https://github.com/obytes/react-native-template-obytes/blob/master/.github/actions/setup-jdk-generate-apk/action.yml). 
I wanted to manually add it to the path but I didn't see JDK in the files. Did you have some informations on how to resolve this issue ?

Have a good day,

Thibaud

**Comment by yjose** [comment]
You probably missed preparing the environment setup.
Make sure to follow this [guide](https://reactnative.dev/docs/set-up-your-environment)
