### ISSUE TITLE
Sentry Integration

### ISSUE THREAD

**Issue by TimorChow** [obytes/react-native-template-obytes#376]
# Summary:
Thank you very much for providing the detailed inheritance approach for sentry in the Doc, but I read the latest sentry documentation and found that the inheritance approach mentioned in the starter Doc has incompatibilities
<img width="1378" alt="image" src="https://github.com/user-attachments/assets/8a2aeb65-e041-4f50-b29f-c712a8ed321a">

## Steps to reproduce:

```

// ReactNavigationInstrumentation
const routingInstrumentation = new Sentry.ReactNavigationInstrumentation();

export const initSentry = () => {
  Sentry.init({
    dsn: Env.SENTRY_DSN,
    // debug: Env.APP_ENV === 'development',
    integrations: [
      new Sentry.ReactNativeTracing({
        routingInstrumentation,
        enableNativeFramesTracking: true,
        // ...
      }),
    ],
  });
};

```

## Additional notes:
version: `"@sentry/react-native": "^6.1.0",`
template version: '6.3.2'

#### Tasks

- [ ] Update sentry initialize function

**Comment by yjose** [comment]
Apparently, the documentation is outdated. Could you please refer to the documents [here](https://docs.sentry.io/platforms/react-native/tracing/instrumentation/expo-router/#initialization) and let me know if they are working as expected?

**Comment by TimorChow** [comment]
@yjose It does work. But I noticed `expo doctor` is recommendding to use `"@sentry/react-native": "~5.24.3"` insteady of `6.1.0`. 

I guess at this point, I would follow expo's recommendation, which means `Obytes Docs` is still correct. Maybe at a note in Sentry page to reminder developer be careful of the version difference while adding Sentry

**Comment by yjose** [comment]
you are right, we should update the installation process to use expo instead of npm
