### ISSUE TITLE
Custom entry point for React Native Track Player

### ISSUE THREAD

**Issue by miladdev85** [obytes/react-native-template-obytes#387]
# Summary:
I need to [create a custom entry point](https://docs.expo.dev/guides/monorepos/#change-default-entrypoint).
Because I have to register a playback service right after registering the main component of the app (typically in index.js file at the root of project):

```
// AppRegistry.registerComponent(...);
TrackPlayer.registerPlaybackService(() => require('./service'));
```
How do I do this?

**Comment by yjose** [comment]
This is mainly related to `expo-router`. You need to create an `index.js` file in the root of the project. Change the `main` entry in your `package.json` to use `index.js` instead of `expo-router/entry`. Then, add the following to your `index.js`:

```js
//index.js
import { registerRootComponent } from "expo";
import { ExpoRoot } from "expo-router";

// Must be exported or Fast Refresh won't update the context
export function App() {
  const ctx = require.context("./src/app"); //Path with src folder
  return <ExpoRoot context={ctx} />;
}

registerRootComponent(App);

// register the player
TrackPlayer.registerPlaybackService(() => require('./service'));

```
More details  [here](https://github.com/expo/router/issues/41)

**Comment by miladdev85** [comment]
> This is mainly related to `expo-router`. You need to create an `index.js` file in the root of the project. Change the `main` entry in your `package.json` to use `index.js` instead of `expo-router/entry`. Then, add the following to your `index.js`:
> 
> ```js
> //index.js
> import { registerRootComponent } from "expo";
> import { ExpoRoot } from "expo-router";
> 
> // Must be exported or Fast Refresh won't update the context
> export function App() {
>   const ctx = require.context("./src/app"); //Path with src folder
>   return <ExpoRoot context={ctx} />;
> }
> 
> registerRootComponent(App);
> 
> // register the player
> TrackPlayer.registerPlaybackService(() => require('./service'));
> ```
> 
> More details [here](https://github.com/expo/router/issues/41)

Thank you very much for your help.
I'm going to create an issue on Expo Router site now.

I get the following error message after doing what you wrote and also what others wrote on the issue you linked to:

```TypeError: func.apply is not a function (it is undefined), js engine: hermes``` 

And also some stuff regarding Reanimated (tag with 1 does not exist)... It seems like Expo Router with custom entry point is not a recommended path to go 🤷‍♂️
