### ISSUE TITLE
Stuck at login screen

### ISSUE THREAD

**Issue by improwise** [obytes/react-native-template-obytes#393]
So, when running a project created you immediately get stuck at the login screen which contains zero information on how to proceed. Also I have not been able to find any information about how to login  / register here on Github or on https://starter.obytes.com/

You can of course easily circumvent this by just removing this from _layout.tsx, 

```
  if (status === 'signOut') {
    return <Redirect href="/login" />;
  }
```

but I would imagine that most people would just have given up by then and moved on to something else like Ignite. 

While I understand the reasoning for including Auth, I would recommend to either not make it default for new projects or at least then include some information to actually get past it. This is extra unfortunate as you can just get a somewhat usable demo running by just removing the above snippet. 

Thanks.

**Comment by yjose** [comment]
Normally, the authentication screen is just a demo. You can enter any login credentials as long as they are valid (the email should be a valid email) and the app should redirect you to the dashboard

I understand your concern, and I think we should add a simple description on the screen itself to reflect the behavior.
Thanks
