### ISSUE TITLE
open app on real phone issues

### ISSUE THREAD

**Issue by Yazington** [obytes/react-native-template-obytes#40]
# Summary:
Hey guys,

I tried to open the app on my phone, but it doesnt work when using `yarn start` . So I tried using `npx expo start` instead. 
when scanning the QR with the first method, nothing happens. When scanning the QR with the second method, I get errors with mmkv package.
![image](https://user-images.githubusercontent.com/33079514/201479994-6856e1aa-2b81-44f7-b831-585870f3eaed.png)

## Expected behavior:
to work on my phone

**Comment by yjose** [comment]
@Yazington we are using a custom dev client for the app. The starter will not work  Expo Go app. we opt for this solution as we are using native libraries such as `react-native-mmkv`.  

if you want to use your phone to develop the app you need to [create a development build](https://docs.expo.dev/development/getting-started/#creating-and-installing-your-first-development-build) first

**Comment by Yazington** [comment]
@yjose if I understand, if I use a custom dev client and use eas to build that client on phone, mmkv wouldnt give any problem right?

**Comment by yjose** [comment]
@Yazington correct 💯

**Comment by Yazington** [comment]
Thank you!
