### ISSUE TITLE
I am getting this issue

### ISSUE THREAD

**Issue by sundargautam18** [obytes/react-native-template-obytes#411]
(NOBRIDGE) LOG  Bridgeless mode is enabled
 INFO 
 💡 JavaScript logs will be removed from Metro in React Native 0.77! Please use React Native DevTools as your default tool. Tip: Type j in the terminal to open (requires Google Chrome or Microsoft Edge).
 (NOBRIDGE) ERROR  Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure you enabled the new architecture (TurboModules) and CodeGen properly generated the react-native-mmkv specs. See https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-apps.md
* Make sure you are using react-native 0.74.0 or higher, because react-native-mmkv is a C++ TurboModule.
* Make sure you rebuilt the app.
* Make sure gradle is synced. [Component Stack]
 (NOBRIDGE) WARN  Route "./(app)/_layout.tsx" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) ERROR  Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure you enabled the new architecture (TurboModules) and CodeGen properly generated the react-native-mmkv specs. See https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-apps.md
* Make sure you are using react-native 0.74.0 or higher, because react-native-mmkv is a C++ TurboModule.
* Make sure you rebuilt the app.
* Make sure gradle is synced. [Component Stack]
 (NOBRIDGE) WARN  Route "./(app)/index.tsx" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) ERROR  Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure you enabled the new architecture (TurboModules) and CodeGen properly generated the react-native-mmkv specs. See https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-apps.md
* Make sure you are using react-native 0.74.0 or higher, because react-native-mmkv is a C++ TurboModule.
* Make sure you rebuilt the app.
* Make sure gradle is synced. [Component Stack]
 (NOBRIDGE) WARN  Route "./(app)/settings.tsx" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) ERROR  Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure you enabled the new architecture (TurboModules) and CodeGen properly generated the react-native-mmkv specs. See https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-apps.md
* Make sure you are using react-native 0.74.0 or higher, because react-native-mmkv is a C++ TurboModule.
* Make sure you rebuilt the app.
* Make sure gradle is synced. [Component Stack]
 (NOBRIDGE) WARN  Route "./(app)/style.tsx" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) ERROR  Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure you enabled the new architecture (TurboModules) and CodeGen properly generated the react-native-mmkv specs. See https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-apps.md
* Make sure you are using react-native 0.74.0 or higher, because react-native-mmkv is a C++ TurboModule.
* Make sure you rebuilt the app.
* Make sure gradle is synced. [Component Stack]
 (NOBRIDGE) WARN  Route "./[...messing].tsx" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) ERROR  Error: The package 'react-native-keyboard-controller' doesn't seem to be linked. Make sure:

- You rebuilt the app after installing the package
- You are not using Expo Go
 [Component Stack]
 (NOBRIDGE) WARN  Route "./_layout.tsx" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) ERROR  Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure you enabled the new architecture (TurboModules) and CodeGen properly generated the react-native-mmkv specs. See https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-apps.md
* Make sure you are using react-native 0.74.0 or higher, because react-native-mmkv is a C++ TurboModule.
* Make sure you rebuilt the app.
* Make sure gradle is synced. [Component Stack]
 (NOBRIDGE) WARN  Route "./feed/[id].tsx" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) ERROR  Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure you enabled the new architecture (TurboModules) and CodeGen properly generated the react-native-mmkv specs. See https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-apps.md
* Make sure you are using react-native 0.74.0 or higher, because react-native-mmkv is a C++ TurboModule.
* Make sure you rebuilt the app.
* Make sure gradle is synced. [Component Stack]
 (NOBRIDGE) WARN  Route "./feed/add-post.tsx" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) ERROR  Error: The package 'react-native-keyboard-controller' doesn't seem to be linked. Make sure:

- You rebuilt the app after installing the package
- You are not using Expo Go
 [Component Stack]
 (NOBRIDGE) WARN  Route "./login.tsx" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) ERROR  Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure you enabled the new architecture (TurboModules) and CodeGen properly generated the react-native-mmkv specs. See https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-apps.md
* Make sure you are using react-native 0.74.0 or higher, because react-native-mmkv is a C++ TurboModule.
* Make sure you rebuilt the app.
* Make sure gradle is synced. [Component Stack]
 (NOBRIDGE) WARN  Route "./onboarding.tsx" is missing the required default export. Ensure a React component is exported as default. [Component Stack]

**Comment by yjose** [comment]
The starter is not working with Expo, please use the client dev for that:
```
pnpm prebuild 
pnpm ios 
```
