### ISSUE TITLE
using without expo

### ISSUE THREAD

**Issue by iamhaaamed** [obytes/react-native-template-obytes#51]
Hello,
Is it possible to use the template without expo?
Because expo currently has some issue with native modules and every time we add a new package it downloads boost_1_76_0.tar.gz:
[[#1148](https://github.com/mrousavy/react-native-vision-camera/issues/1148)](https://github.com/mrousavy/react-native-vision-camera/issues/1148)

**Comment by Pkcarreno** [comment]
this file is also used by `react-native-mmkv`, did you have any problem with this library?

**Comment by iamhaaamed** [comment]
yeah, same problem with `react-native-mmkv`

**Comment by Pkcarreno** [comment]
and the workaround doesn't work for you?

**Comment by iamhaaamed** [comment]
the workaround is working for me, but as mentioned in that issue, that workaround is a temporarily workaround...

**Comment by Pkcarreno** [comment]
that is correct, to answer your question, I don't use expo but I have applied many of the concepts and libraries of this template to my project, so it is possible to use it without expo, you just have to change some libraries that it takes from expo, you could check previous versions that used react native and go from there.

also this problem of the .tar file also exists in react native cli

**Comment by yjose** [comment]
Thank you @Pkcarreno  for your response. 
@iamhaaamed Just want to mention that we added more docs on [why we are using expo instead of a simple cli ](https://starter.obytes.com/docs/overview#-why-expo) as well as this issue exist on the CLI  too and i think it has been fixed with the last expo sdk
