### ISSUE TITLE
screen content overlap with header on android

### ISSUE THREAD

**Issue by iamhaaamed** [obytes/react-native-template-obytes#58]
# Summary:
if a screen have a header, the top content of the screen is going behind the header on Android. 

## Steps to reproduce:
run the app on android and going to a screen with header.

## Expected behavior:
content of the screen should not going behind the header on Android. 

## Additional notes:
if the react-navigation package updated, issue will be fixed.

**Comment by SihamBen** [comment]
@iamhaaamed  in which phone  did you to encounter this please ?

**Comment by iamhaaamed** [comment]
@SihamBen in Nexus One and API Level 30
